### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by gusshawstewart** [githubschool/open-door#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'Unwatch' button and selecting either the 'Not watching' or 'Ignoring' option.

**Comment by gusshawstewart** [comment]
hello!

**Comment by Imitiyaz-1552789** [comment]
test 123

**Comment by krishna-code-hub** [comment]
Hi

**Comment by spqi** [comment]
hi everyone

**Comment by 1499715** [comment]
Hi

**Comment by Kalees4u** [comment]
Hello, kalees here

**Comment by rangarajans1** [comment]
Great training!

**Comment by 1604746** [comment]
Welcome to Git

**Comment by kksumit** [comment]
Hi great start ...

**Comment by 1626125** [comment]
Hi all

**Comment by stephenranjit** [comment]
Test, test

**Comment by ta-suresh** [comment]
:)

**Comment by charanyaramanathan** [comment]
Hello, Good one

**Comment by 1528877** [comment]
Hi Hi :)

**Comment by gusshawstewart** [comment]
@gusshawstewart what do you think of xyz?

**Comment by Lowell7im** [comment]
Test

**Comment by sagar19shah-sc** [comment]
hello..

**Comment by tanchenwei-1512071** [comment]
hello

**Comment by Aruna1589844** [comment]
Hello

**Comment by Nandhalal** [comment]
Got it :)

**Comment by Jayanthi6** [comment]
I created account

**Comment by srikisc** [comment]
good collab space..

**Comment by Kalees4u** [comment]
Hi

**Comment by sarasahg** [comment]
hi

**Comment by kksumit** [comment]
back in 20min

**Comment by 1633605-Phaneendra** [comment]
test

**Comment by iwillcode1010** [comment]
Test Comment

**Comment by 1597018** [comment]
add me

**Comment by sebitaToString** [comment]
this is a commentary
